### PR TITLE
Add osx-arm64 build

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@maxb2 if you want I can add myself to the maintainers list, happy to help with maintenance!

**Comment by maxb2** [comment]
That would be great if you added yourself!

**Comment by mikemhenry** [comment]
@maxb2 Done! Thanks!

**Comment by mikemhenry** [comment]
hmmm,
```
+ python tests/citeproc-test.py --no-update
Cloning the test-suite repository...
git clone https://github.com/citation-style-language/test-suite.git $SRC_DIR/tests/test-suite
Checking out the specified commit...
/home/conda/feedstock_root/build_artifacts/citeproc-py_1715349814197/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/citeproc/source/__init__.py:27: UserWarning: The following arguments for Name are unsupported: isInstitution
  warn('The following arguments for {} are '.format(cls_name) +
/home/conda/feedstock_root/build_artifacts/citeproc-py_1715349814197/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/citeproc/source/__init__.py:27: UserWarning: The following arguments for Reference are unsupported: reviewed_author
  warn('The following arguments for {} are '.format(cls_name) +
/home/conda/feedstock_root/build_artifacts/citeproc-py_1715349814197/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/citeproc/source/__init__.py:27: UserWarning: The following arguments for Reference are unsupported: journalAbbreviation
  warn('The following arguments for {} are '.format(cls_name) +
/home/conda/feedstock_root/build_artifacts/citeproc-py_1715349814197/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/citeproc/source/__init__.py:27: UserWarning: The following arguments for CitationItem are unsupported: position
  warn('The following arguments for {} are '.format(cls_name) +
/home/conda/feedstock_root/build_artifacts/citeproc-py_1715349814197/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/citeproc/source/__init__.py:27: UserWarning: The following arguments for CitationItem are unsupported: position, first_reference_note_number
  warn('The following arguments for {} are '.format(cls_name) +
/home/conda/feedstock_root/build_artifacts/citeproc-py_1715349814197/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/citeproc/source/__init__.py:27: UserWarning: The following arguments for Reference are unsupported: label
  warn('The following arguments for {} are '.format(cls_name) +
/home/conda/feedstock_root/build_artifacts/citeproc-py_1715349814197/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.10/site-packages/citeproc/source/__init__.py:27: UserWarning: The following arguments for Reference are unsupported: multi
All is well.

The test-suite repository has updates! Consider updating the test script.
+ exit 0
```

not sure if that is a problem or not, but now I am getting some CI failures that might be from this build 

https://github.com/OpenFreeEnergy/openfe/actions/runs/9115100379/job/25060596881?pr=853

**Comment by mikemhenry** [comment]
false alarm, it looks the new new duecredit release (`0.10.0`) isn't working/has some issues

**Comment by maxb2** [comment]
Are we good to keep this merged? On a related note, would you like to take over this repo? I needed for a work project a long time ago and no longer use it.

**Comment by mikemhenry** [comment]
@maxb2 I don't see a way to do it with a bot request https://conda-forge.org/docs/maintainer/infrastructure/#admin-web-services

But next time we get a PR that does a new build I can remove you from the maintainers list

**Pull request merged**
